const ROLES = {
  ADMIN: "ADMIN",
  HR_MANAGER: "HR_MANAGER",
  HR_PAYROLL_MANAGER: "HR_PAYROLL_MANAGER",
  HR_PAYROLL_USER: "HR_PAYROLL_USER",
  EMPLOYEE: "EMPLOYEE",
};

const ADMIN_ROLES = [
  ROLES.ADMIN,
];

const HR_ROLES = [
  ROLES.ADMIN,
  ROLES.HR_MANAGER,
  ROLES.HR_PAYROLL_MANAGER,
];

const PAYROLL_MANAGER_ROLES = [
  ROLES.ADMIN,
  ROLES.HR_PAYROLL_MANAGER,
];

const PAYROLL_ROLES = [
  ROLES.ADMIN,
  ROLES.HR_PAYROLL_MANAGER,
  ROLES.HR_PAYROLL_USER,
];

const EMPLOYEE_ACCESS_ROLES = [
  ...PAYROLL_ROLES,
  ROLES.EMPLOYEE,
];

module.exports = {
  ROLES,
  ADMIN_ROLES,
  HR_ROLES,
  PAYROLL_MANAGER_ROLES,
  PAYROLL_ROLES,
  EMPLOYEE_ACCESS_ROLES,
};